# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OppHack19T2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OppHack19T2
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Cosmos', '~> 20.0'
  pod 'TinyConstraints'
  pod 'Firebase/InAppMessagingDisplay'

end
